apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-ppc64le-image
spec:
  params:
    - name: pathToDockerFile-cross-build
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.cross-build-docker-source.path)/Cross-Build/Dockerfile
  resources:
    inputs:
      - name: cross-build-docker-source
        type: git
  steps:
    - name: cross-build
      image: quay.io/mayurwaghmode111/buildah-with-podman
      script: |
        #!/bin/sh
        podman run --rm --privileged docker.io/multiarch/qemu-user-static:register --reset
        buildah bud -f $(params.pathToDockerFile-cross-build) -t "ppc64le"
        buildah from localhost/ppc64le
        buildah commit ppc64le-working-container ppc64lecntwithincnt
        buildah login -u mayurwaghmode111+test -p X92E11Y7OV17QBLJRJT2URECDG11J5LY67BKFBAG5ASZMMWO9667YHO9LFOKCAGW quay.io
        buildah push ppc64lecntwithincnt quay.io/mayurwaghmode111/ppc64le-container-built-from-kaniko-buildah
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}


