apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-ppc64le-image
spec:
  params:
    - name: pathToDockerFile-cross-build
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.cross-build-docker-source.path)/Cross-Build/Dockerfile
    - name: IMAGE
      description: Reference of the image buildah will produce.
    - name: CONTAINER
      description: Reference of the container buildah will produce.
    - name: REMOTE_REPO_URL
      description: Reference of the remote repository where you want to push the repo
    - name: USERNAME
      description: Username of the remote repository
    - name: PASSWORD
      description: Password of the remote repository
  resources:
    inputs:
      - name: cross-build-docker-source
        type: git
  steps:
    - name: cross-build
      image: quay.io/buildah/stable
      script: |
        #!/bin/sh
        #Building the Dockerfile
        buildah bud -f $(params.pathToDockerFile-cross-build) -t $(params.IMAGE)  
        buildah from localhost/$(params.IMAGE)
        buildah commit $(params.IMAGE)-working-container $(params.CONTAINER)
        #Login to the remote Quay repository
        buildah login -u $(params.USERNAME) -p $(params.PASSWORD) quay.io
        #Pushing the image to the Quay repository
        buildah push $(params.CONTAINER) $(params.REMOTE_REPO_URL)
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
