apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-docker-image-from-git-source-pipeline-run
spec:
  serviceAccountName: quay-service
  pipelineRef:
    name: build-docker-image-from-git-source-pipeline
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    - name: docker-source
      resourceRef:
        name: buildahgit
    - name: builtImage
      resourceRef:
        name: buildahimage
