apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ppc64le-image-from-tekton-pipeline
spec:
  params:
    - name: pathToDockerFile
  resources:

      - name: docker-source
        type: git
      - name: builtImage
        type: image
      - name: cross-build-docker-source
        type: git
  tasks:
    - name: build-docker-image-from-git-source
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: docker-source
        outputs:
          - name: builtImage
            resource: builtImage

    - name: build-ppc64le-image
      taskRef:
        name: build-ppc64le-image
       resources:
        inputs:
          - name: cross-build-docker-source
            resource: cross-build-docker-source
      runAfter:
          - build-docker-image-from-git-source
     

