apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ppc64le-image-from-tekton-pipeline
spec:
  params:
    - name: pathToDockerfile-cross-build
  resources:
      - name: cross-build-docker-source
        type: git
  tasks:
    - name: build-ppc64le-image
      taskRef:
        name: build-ppc64le-image
      resources:
        inputs:
          - name: cross-build-docker-source
            resource: cross-build-docker-source
      params:
        - name: IMAGE
          value: ppc64le
        - name: CONTAINER
          value: ppc64lecntwithincnt
        - name: REMOTE_REPO_URL
          value: {Your_Remote_Repository_URL}
        - name: USERNAME
          value: {Your_Remote_Repository_Username}
        - name: PASSWORD
          value: {Your_Remote_Repository_Password}

