apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-docker-image-from-git-source-pipeline
spec:
  params:
    - name: pathToDockerFile
  resources:

      - name: docker-source
        type: git
      - name: builtImage
        type: image
  tasks:
    - name: build-docker-image-from-git-source
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: docker-source
        outputs:
          - name: builtImage
            resource: builtImage

    - name: task-build
      taskRef:
        name: task-build
      runAfter:
          - build-docker-image-from-git-source
     

