apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: buildahgit
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/mayurwaghmode/cross-building-containers.git
