apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cross-build-git
spec:
  type: git
  params:
    - name: revision
      value: tekton-buildah
    - name: url
      value: https://github.com/mayurwaghmode/cross-building-containers.git
